# Generated by Django 5.2 on 2025-05-05 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_topuprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topuprequest',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='topuprequest',
            name='response_message',
        ),
        migrations.RemoveField(
            model_name='topuprequest',
            name='status',
        ),
    ]
